name: notewave
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_quill: ^10.8.5
  flutter_quill_extensions: ^10.8.5
  shared_preferences: ^2.3.3
  intl: ^0.19.0
  speech_to_text: ^7.0.0
  flutter_speed_dial: ^7.0.0
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  firebase_database: ^11.2.0
  cloud_firestore: ^5.6.0
  flutter_keyboard_visibility: ^6.0.0
  pdf: ^3.11.1
  flutter_quill_to_pdf: ^2.2.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true
