// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBRL5uBDFqd99ZPG9pTIDdTOEPKfyoejo',
    appId: '1:247595491349:ios:27d3ccf2d84964c5142e1c',
    messagingSenderId: '247595491349',
    projectId: 'notewave-16d0f',
    storageBucket: 'notewave-16d0f.firebasestorage.app',
    iosBundleId: 'com.example.notewave',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBRL5uBDFqd99ZPG9pTIDdTOEPKfyoejo',
    appId: '1:247595491349:ios:27d3ccf2d84964c5142e1c',
    messagingSenderId: '247595491349',
    projectId: 'notewave-16d0f',
    storageBucket: 'notewave-16d0f.firebasestorage.app',
    iosBundleId: 'com.example.notewave',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDylW3-wPAfjP4H-xjfrBOcU5uqsOpYbyQ',
    appId: '1:247595491349:web:91371963125b441e142e1c',
    messagingSenderId: '247595491349',
    projectId: 'notewave-16d0f',
    authDomain: 'notewave-16d0f.firebaseapp.com',
    storageBucket: 'notewave-16d0f.firebasestorage.app',
    measurementId: 'G-VR4HEDQSDM',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDylW3-wPAfjP4H-xjfrBOcU5uqsOpYbyQ',
    appId: '1:247595491349:web:91371963125b441e142e1c',
    messagingSenderId: '247595491349',
    projectId: 'notewave-16d0f',
    authDomain: 'notewave-16d0f.firebaseapp.com',
    storageBucket: 'notewave-16d0f.firebasestorage.app',
    measurementId: 'G-VR4HEDQSDM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe0ysFREWsljOnAg0knudwi-j5AVPZxys',
    appId: '1:247595491349:android:54e8b7b5a0074080142e1c',
    messagingSenderId: '247595491349',
    projectId: 'notewave-16d0f',
    storageBucket: 'notewave-16d0f.firebasestorage.app',
  );

}